// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh82JdbYNQPCa_fStiGuJGkN-bG4q4Z0U',
    appId: '1:234903321426:web:d5d9d175a129a347b0188b',
    messagingSenderId: '234903321426',
    projectId: 'noskillwork-45d8e',
    authDomain: 'noskillwork-45d8e.firebaseapp.com',
    storageBucket: 'noskillwork-45d8e.firebasestorage.app',
    measurementId: 'G-GBLK9Y6Q71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1exlKFiq40SaD2o0PpoEUDngk5RlXfAA',
    appId: '1:234903321426:android:2903d2669a223946b0188b',
    messagingSenderId: '234903321426',
    projectId: 'noskillwork-45d8e',
    storageBucket: 'noskillwork-45d8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs2ns__gryboUErfRoMV1EGYizavcS08s',
    appId: '1:234903321426:ios:aa39b1caa42be944b0188b',
    messagingSenderId: '234903321426',
    projectId: 'noskillwork-45d8e',
    storageBucket: 'noskillwork-45d8e.firebasestorage.app',
    iosBundleId: 'com.example.nsw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs2ns__gryboUErfRoMV1EGYizavcS08s',
    appId: '1:234903321426:ios:aa39b1caa42be944b0188b',
    messagingSenderId: '234903321426',
    projectId: 'noskillwork-45d8e',
    storageBucket: 'noskillwork-45d8e.firebasestorage.app',
    iosBundleId: 'com.example.nsw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh82JdbYNQPCa_fStiGuJGkN-bG4q4Z0U',
    appId: '1:234903321426:web:6c3f16f760b5d71fb0188b',
    messagingSenderId: '234903321426',
    projectId: 'noskillwork-45d8e',
    authDomain: 'noskillwork-45d8e.firebaseapp.com',
    storageBucket: 'noskillwork-45d8e.firebasestorage.app',
    measurementId: 'G-8HKR9R0060',
  );
}
